# Generated by Django 4.2.4 on 2023-08-08 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='foto_vaga',
            field=models.ImageField(blank=True, upload_to='pictures/Y%/%m/%d'),
        ),
    ]
