# Generated by Django 4.2.4 on 2023-08-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0004_alter_vaga_foto_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='foto_vaga',
            field=models.ImageField(blank=True, upload_to='fotos/'),
        ),
    ]
